export const statFieldPresets = [
  "FullDPS",
  "TotalEHP",
  "AverageDamage",
  "Speed",
  "Life",
  "EnergyShield",
  "FireResist",
  "ColdResist",
  "LightningResist",
  "ChaosResist",
] as const;

export const equipmentSlots = [
  "",
  "Weapon 1",
  "Weapon 2",
  "Helmet",
  "Body Armour",
  "Gloves",
  "Boots",
  "Amulet",
  "Ring 1",
  "Ring 2",
  "Belt",
  "Flask 1",
  "Flask 2",
  "Flask 3",
  "Flask 4",
  "Flask 5",
] as const;

export const configFieldDefinitions = [
  { key: "bandit", label: "Bandit", kind: "text" },
  { key: "pantheonMajorGod", label: "Pantheon Major God", kind: "text" },
  { key: "pantheonMinorGod", label: "Pantheon Minor God", kind: "text" },
  { key: "enemyLevel", label: "Enemy Level", kind: "number" },
  { key: "enemyFireResist", label: "Enemy Fire Resist", kind: "number" },
  { key: "enemyColdResist", label: "Enemy Cold Resist", kind: "number" },
  { key: "enemyLightningResist", label: "Enemy Lightning Resist", kind: "number" },
  { key: "enemyChaosResist", label: "Enemy Chaos Resist", kind: "number" },
  { key: "enemyArmour", label: "Enemy Armour", kind: "number" },
  { key: "enemyEvasion", label: "Enemy Evasion", kind: "number" },
  { key: "enemyIsBoss", label: "Enemy Is Boss", kind: "text" },
  { key: "usePowerCharges", label: "Use Power Charges", kind: "boolean" },
  { key: "useFrenzyCharges", label: "Use Frenzy Charges", kind: "boolean" },
  { key: "useEnduranceCharges", label: "Use Endurance Charges", kind: "boolean" },
  { key: "conditionShockedGround", label: "Condition Shocked Ground", kind: "boolean" },
  { key: "conditionFortify", label: "Condition Fortify", kind: "boolean" },
  { key: "conditionLeeching", label: "Condition Leeching", kind: "boolean" },
  { key: "buffOnslaught", label: "Buff Onslaught", kind: "boolean" },
] as const;
